def menu_relatorios():
    print('=' * 50)
    print('=' * 20, 'MENU RELATÓRIOS', '=' * 20)
    print('=' * 50)
    print('[1] Relatórios de alunos')
    print('[2] Relatórios financeiros')
    print('[3] Relatórios de professores')
    print('[4] relatórios de mensalidades')
    print('[0] Voltar')
    print("=" * 50)
    return int(input('Selecione uma opção: '))

def menu_relatorios_alunos():
    print('=' * 50)
    print('=' * 20, 'RELATÓRIOS DE ALUNOS', '=' * 20)
    print('=' * 50)
    print('[1] Aluno por plano')
    print('[2] Alunos em ordem alfabética')
    print('[3] Alunos com mensalidades pendentes')
    print('[4] Quantidade de alunos por plano')
    print('[0] Voltar')
    print("=" * 50)
    return int(input('Selecione uma opção: '))

def menu_relatorios_financeiros():
    print('=' * 50)
    print('=' * 20, 'RELATÓRIOS FINANCEIROS', '=' * 20)
    print('=' * 50)
    print('[1] Receita total')
    print('[2] Receita por período')
    print('[3] Mensalidades pagas')
    print('[4] Mensalidades pendentes')
    print('[4] Total pendente de recebimento')
    print('[0] Voltar')
    print("=" * 50)
    return int(input('Selecione uma opção: '))

def menu_relatorios_professores():
    print('=' * 50)
    print('=' * 20, 'RELATÓRIOS DE PROFESSORES', '=' * 20)
    print('=' * 50)
    print('[1] Professores em ordem alfabética')
    print('[2] professores por especialidade')
    print('[0] Voltar')
    print("=" * 50)
    return int(input('Selecione uma opção: '))

def menu_relatorios_mensalidades():
    print('=' * 50)
    print('=' * 20, 'RELATÓRIOS DE MENSALIDADES', '=' * 20)
    print('=' * 50)
    print('[1] Mensalidades por mês')
    print('[2] Mensalidades pagas')
    print('[3] Mensalidades pendentes')
    print('[4] Percentual de inadimplência')
    print('[0] Voltar')
    print("=" * 50)
    return int(input('Selecione uma opção: '))